config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :exposition
    validates :image
  end

  # has_many :comments
  # belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  # has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: [:nickname, :email, :birthday, :lastname, :firstname, :lastname_kana, :firstname_kana]
    )
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.order('created_at DESC')
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :exposition, :image) # .merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Platt2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <%# render "shared/header" %>
  </header>
    <%= yield %>
    <footer>
    <%= render "shared/footer" %>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<% if user_signed_in? %> 
<footer class ="footer">
<nav class ="global-nav">
  <ul class="nav-list">
    <li class="nav-item">
      <%=link_to root_path do %>
        <i class="fas fa-home">
				<%= image_tag 'test1.png' , size: '40x45' %>
				</i>
        <span>Home</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_tweet_path do %>
        <i class="fas fa-cart-arrow-down">
				<%= image_tag 'search2.png' , size: '40x45' %>
				</i>
        <span>Search</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_tweet_path do %>
        <i class="fas fa-cart-arrow-down">
				<%= image_tag 'test5.png' , size: '40x45' %>
				</i>
        <span>New</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_tweet_path do %>
        <i class="fas fa-cart-arrow-down">
				<%= image_tag 'test6.png' , size: '40x45' %>
				</i>
        <span>Notice</span>
      <% end %>
    </li>
  </ul>
</nav>
</footer>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header2">
    <h1 class="grid-1"><a href="/">Platt2</a></h1>
    <% if user_signed_in? %>
       <div class="user_glovel">
          <div class="user_nav">
            <%= link_to current_user.nickname, "/users/#{current_user.id}", class: "post" %>
          </div>
        <% else %>
          <div class="user_nav2">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        </div>
        <% end %>
  </div>
</header>

app/views/tweets/index.html.erb
<%= render "shared/header" %>

<div class="type1">
  <% @tweets.each do |tweet| %>
  <div>
  <%= tweet.title %>
  </div>
  <div>
  <%# tweet.user.name %>
  </div>
  <div>
  <%= image_tag tweet.image, class: 'tweet-img' if tweet.image.attached? %>
  </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="contents_row">
  <div class="container">
    <%= form_with model: @tweet, local: true do |form| %>
    <%= form.file_field :image %>
    <%= form.text_field :title %>
    <%= form.text_area :exposition %>
    <%= form.submit "アップロード"%>
    <% end %>
  </div>
</div>